services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-controller
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
  
  ssh-agent:
    image: jenkins/ssh-agent
    container_name: jenkins-ssh-agent
    ports:
      - "2200:22"